import type { Category } from "@/entities/categories";
import type { Product } from "@/entities/products";
import pacificoHero from "@/shared/assets/pacifico-hero.png";

// No backend yet — this catalog is placeholder data shaped exactly like the
// real API contract (entities/products, entities/categories) so swapping in
// the real fetch hooks later is a drop-in replacement. All products share the
// same hero photo as a stand-in; there's no real per-dish photography yet.

const MOCK_TIMESTAMP = "2026-01-01T00:00:00.000Z";

export const MOCK_CATEGORIES: Category[] = [
	{
		id: "cat-mariscos",
		name: "Mariscos",
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "cat-platos",
		name: "Platos preparados",
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "cat-bebidas",
		name: "Bebidas",
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "cat-postres",
		name: "Postres",
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
];

export const MOCK_TAGS: string[] = [
	"seafood",
	"shrimp",
	"traditional",
	"pacific-food",
	"coconut",
	"fried",
	"soup",
	"rice",
];

export const MOCK_PRODUCTS: Product[] = [
	{
		id: "prod-encocado-camaron",
		name: "Encocado de camarón",
		description: "Camarones frescos en salsa de coco, tomate y cilantro.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 35000,
		stock: 8,
		categoryId: "cat-mariscos",
		cookId: "cook-maria",
		availability: "available",
		tags: ["seafood", "shrimp", "coconut", "traditional"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-sancocho-pescado",
		name: "Sancocho de pescado",
		description: "Sopa tradicional con pescado, plátano, yuca y cilantro.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 28000,
		stock: 12,
		categoryId: "cat-platos",
		cookId: "cook-maria",
		availability: "available",
		tags: ["seafood", "soup", "traditional"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-arroz-atapado",
		name: "Arroz atapado",
		description: "Arroz cocido a fuego lento con costilla y verde.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 18000,
		stock: 20,
		categoryId: "cat-platos",
		cookId: "cook-rosa",
		availability: "available",
		tags: ["rice", "traditional", "pacific-food"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-patacones-camaron",
		name: "Patacones con camarón",
		description: "Patacones crocantes cubiertos con camarón al ajillo.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 25000,
		stock: 15,
		categoryId: "cat-mariscos",
		cookId: "cook-rosa",
		availability: "available",
		tags: ["seafood", "shrimp", "fried"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-ceviche-camaron",
		name: "Ceviche de camarón",
		description: "Camarón fresco marinado en limón, cebolla y cilantro.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 32000,
		categoryId: "cat-mariscos",
		cookId: "cook-maria",
		availability: "made_to_order",
		minimumOrderQuantity: 3,
		preparationTimeHours: 4,
		tags: ["seafood", "shrimp", "traditional"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-viche",
		name: "Viche del Pacífico",
		description: "Bebida ancestral destilada de caña con toque de coco.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 15000,
		stock: 30,
		categoryId: "cat-bebidas",
		cookId: "cook-rosa",
		availability: "available",
		tags: ["traditional", "pacific-food", "coconut"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-tamal-pescado",
		name: "Tamal de pescado",
		description: "Tamal envuelto en hoja de plátano con pescado y arroz.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 22000,
		categoryId: "cat-platos",
		cookId: "cook-maria",
		availability: "made_to_order",
		minimumOrderQuantity: 5,
		preparationTimeHours: 24,
		tags: ["seafood", "traditional", "pacific-food"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
	{
		id: "prod-aborrajados",
		name: "Aborrajados con queso",
		description: "Plátano maduro frito relleno de queso costeño.",
		images: [{ id: "img-pacifico-hero", url: pacificoHero, publicId: "mock/pacifico-hero" }],
		price: 12000,
		stock: 25,
		categoryId: "cat-postres",
		cookId: "cook-rosa",
		availability: "available",
		tags: ["fried", "traditional"],
		isAvailable: true,
		isActive: true,
		createdAt: MOCK_TIMESTAMP,
		updatedAt: MOCK_TIMESTAMP,
	},
];
